//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Efes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atlas.Efes.Resources.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Oluştur.
        /// </summary>
        public static string Create_Invoice {
            get {
                return ResourceManager.GetString("Create_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Birimi.
        /// </summary>
        public static string Invoice_Currency {
            get {
                return ResourceManager.GetString("Invoice_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özelliştirme Numarası.
        /// </summary>
        public static string Invoice_Custom_Id {
            get {
                return ResourceManager.GetString("Invoice_Custom_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Tarihi.
        /// </summary>
        public static string Invoice_Date {
            get {
                return ResourceManager.GetString("Invoice_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taslaklar.
        /// </summary>
        public static string Invoice_Drafts {
            get {
                return ResourceManager.GetString("Invoice_Drafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Kuru.
        /// </summary>
        public static string Invoice_Exchange_Rate {
            get {
                return ResourceManager.GetString("Invoice_Exchange_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Numarası.
        /// </summary>
        public static string Invoice_Number {
            get {
                return ResourceManager.GetString("Invoice_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Islemleri.
        /// </summary>
        public static string Invoice_Process {
            get {
                return ResourceManager.GetString("Invoice_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senaryo.
        /// </summary>
        public static string Invoice_Scenario {
            get {
                return ResourceManager.GetString("Invoice_Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Tipi.
        /// </summary>
        public static string Invoice_Type {
            get {
                return ResourceManager.GetString("Invoice_Type", resourceCulture);
            }
        }
    }
}
