//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Efes.OracleClient.OracleServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="creditCardInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class creditCardInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string clientIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cvvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string expMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string expYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string holderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tcknField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vknField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clientIP {
            get {
                return this.clientIPField;
            }
            set {
                if ((object.ReferenceEquals(this.clientIPField, value) != true)) {
                    this.clientIPField = value;
                    this.RaisePropertyChanged("clientIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cvv {
            get {
                return this.cvvField;
            }
            set {
                if ((object.ReferenceEquals(this.cvvField, value) != true)) {
                    this.cvvField = value;
                    this.RaisePropertyChanged("cvv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string expMonth {
            get {
                return this.expMonthField;
            }
            set {
                if ((object.ReferenceEquals(this.expMonthField, value) != true)) {
                    this.expMonthField = value;
                    this.RaisePropertyChanged("expMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string expYear {
            get {
                return this.expYearField;
            }
            set {
                if ((object.ReferenceEquals(this.expYearField, value) != true)) {
                    this.expYearField = value;
                    this.RaisePropertyChanged("expYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string holder {
            get {
                return this.holderField;
            }
            set {
                if ((object.ReferenceEquals(this.holderField, value) != true)) {
                    this.holderField = value;
                    this.RaisePropertyChanged("holder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string number {
            get {
                return this.numberField;
            }
            set {
                if ((object.ReferenceEquals(this.numberField, value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tckn {
            get {
                return this.tcknField;
            }
            set {
                if ((object.ReferenceEquals(this.tcknField, value) != true)) {
                    this.tcknField = value;
                    this.RaisePropertyChanged("tckn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vkn {
            get {
                return this.vknField;
            }
            set {
                if ((object.ReferenceEquals(this.vknField, value) != true)) {
                    this.vknField = value;
                    this.RaisePropertyChanged("vkn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Params", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Efes.OracleClient.OracleServiceProxy.creditCardInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Efes.OracleClient.OracleServiceProxy.Params[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Efes.OracleClient.OracleServiceProxy.sessionInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Efes.OracleClient.OracleServiceProxy.ServiceResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    public partial class Params : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParamNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParamTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ParamValField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParamName {
            get {
                return this.ParamNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParamNameField, value) != true)) {
                    this.ParamNameField = value;
                    this.RaisePropertyChanged("ParamName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParamType {
            get {
                return this.ParamTypeField;
            }
            set {
                if ((this.ParamTypeField.Equals(value) != true)) {
                    this.ParamTypeField = value;
                    this.RaisePropertyChanged("ParamType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object ParamVal {
            get {
                return this.ParamValField;
            }
            set {
                if ((object.ReferenceEquals(this.ParamValField, value) != true)) {
                    this.ParamValField = value;
                    this.RaisePropertyChanged("ParamVal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sessionInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class sessionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string authKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string infoMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int paymentBankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string salesMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string authKey {
            get {
                return this.authKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.authKeyField, value) != true)) {
                    this.authKeyField = value;
                    this.RaisePropertyChanged("authKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string company {
            get {
                return this.companyField;
            }
            set {
                if ((object.ReferenceEquals(this.companyField, value) != true)) {
                    this.companyField = value;
                    this.RaisePropertyChanged("company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string infoMail {
            get {
                return this.infoMailField;
            }
            set {
                if ((object.ReferenceEquals(this.infoMailField, value) != true)) {
                    this.infoMailField = value;
                    this.RaisePropertyChanged("infoMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int paymentBank {
            get {
                return this.paymentBankField;
            }
            set {
                if ((this.paymentBankField.Equals(value) != true)) {
                    this.paymentBankField = value;
                    this.RaisePropertyChanged("paymentBank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string salesMail {
            get {
                return this.salesMailField;
            }
            set {
                if ((object.ReferenceEquals(this.salesMailField, value) != true)) {
                    this.salesMailField = value;
                    this.RaisePropertyChanged("salesMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResult", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Efes.OracleClient.OracleServiceProxy.creditCardInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Efes.OracleClient.OracleServiceProxy.Params[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Efes.OracleClient.OracleServiceProxy.Params))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Efes.OracleClient.OracleServiceProxy.sessionInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    public partial class ServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet ResultSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrMessage {
            get {
                return this.ErrMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrMessageField, value) != true)) {
                    this.ErrMessageField = value;
                    this.RaisePropertyChanged("ErrMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet ResultSet {
            get {
                return this.ResultSetField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultSetField, value) != true)) {
                    this.ResultSetField = value;
                    this.RaisePropertyChanged("ResultSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OracleServiceProxy.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreditCardPayment", ReplyAction="http://tempuri.org/IService1/CreditCardPaymentResponse")]
        bool CreditCardPayment(int BankId, string refNo, decimal amount, Atlas.Efes.OracleClient.OracleServiceProxy.creditCardInfo cardInfo, ref string errorMessage, ref string provisionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreditCardPaymentRefund", ReplyAction="http://tempuri.org/IService1/CreditCardPaymentRefundResponse")]
        bool CreditCardPaymentRefund(int BankId, string refNo, decimal amount, Atlas.Efes.OracleClient.OracleServiceProxy.creditCardInfo cardInfo, ref string errorMessage, ref string provisionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAnyProcByParams", ReplyAction="http://tempuri.org/IService1/getAnyProcByParamsResponse")]
        System.Data.DataSet getAnyProcByParams(string procName, Atlas.Efes.OracleClient.OracleServiceProxy.Params[] lstParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getMultipleCursor", ReplyAction="http://tempuri.org/IService1/getMultipleCursorResponse")]
        System.Data.DataSet getMultipleCursor(string procName, Atlas.Efes.OracleClient.OracleServiceProxy.Params[] lstParams, string[] cursors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getReport", ReplyAction="http://tempuri.org/IService1/getReportResponse")]
        System.Data.DataSet getReport(string procName, Atlas.Efes.OracleClient.OracleServiceProxy.Params[] lstParams, int cacheTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDATA", ReplyAction="http://tempuri.org/IService1/GetDATAResponse")]
        System.Data.DataSet GetDATA(string LoadSP_, string SelectSQL_, string PrimaryKeyColumn, decimal PKID_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ServerInsUpd", ReplyAction="http://tempuri.org/IService1/ServerInsUpdResponse")]
        decimal ServerInsUpd(string TableName, string SaveSP, string PrimaryKeyColumn, int PKVALUE, Atlas.Efes.OracleClient.OracleServiceProxy.Params[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAnyProcByNamelessParam", ReplyAction="http://tempuri.org/IService1/getAnyProcByNamelessParamResponse")]
        System.Data.DataSet getAnyProcByNamelessParam(string procName, Atlas.Efes.OracleClient.OracleServiceProxy.Params[] lstParams);
        
        // CODEGEN: Generating message contract since the wrapper name (transactionApprover) of message transactionApprover does not match the default value (getCredential)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCredential", ReplyAction="http://tempuri.org/IService1/getCredentialResponse")]
        Atlas.Efes.OracleClient.OracleServiceProxy.sessionInfo1 getCredential(Atlas.Efes.OracleClient.OracleServiceProxy.transactionApprover request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetServiceResult", ReplyAction="http://tempuri.org/IService1/GetServiceResultResponse")]
        Atlas.Efes.OracleClient.OracleServiceProxy.ServiceResult GetServiceResult(string procName, Atlas.Efes.OracleClient.OracleServiceProxy.Params[] lstParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetServiceResultMulti", ReplyAction="http://tempuri.org/IService1/GetServiceResultMultiResponse")]
        Atlas.Efes.OracleClient.OracleServiceProxy.ServiceResult GetServiceResultMulti(string procName, Atlas.Efes.OracleClient.OracleServiceProxy.Params[] lstParams, string[] lstCursors);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transactionApprover", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class transactionApprover {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Atlas.Efes.OracleClient.OracleServiceProxy.sessionInfo affiliateApprover;
        
        public transactionApprover() {
        }
        
        public transactionApprover(Atlas.Efes.OracleClient.OracleServiceProxy.sessionInfo affiliateApprover) {
            this.affiliateApprover = affiliateApprover;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sessionInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class sessionInfo1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string IP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string authKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string infoMail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int paymentBank;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string salesMail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string userName;
        
        public sessionInfo1() {
        }
        
        public sessionInfo1(string IP, string authKey, string company, string infoMail, string password, int paymentBank, string salesMail, string userName) {
            this.IP = IP;
            this.authKey = authKey;
            this.company = company;
            this.infoMail = infoMail;
            this.password = password;
            this.paymentBank = paymentBank;
            this.salesMail = salesMail;
            this.userName = userName;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Atlas.Efes.OracleClient.OracleServiceProxy.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Atlas.Efes.OracleClient.OracleServiceProxy.IService1>, Atlas.Efes.OracleClient.OracleServiceProxy.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreditCardPayment(int BankId, string refNo, decimal amount, Atlas.Efes.OracleClient.OracleServiceProxy.creditCardInfo cardInfo, ref string errorMessage, ref string provisionCode) {
            return base.Channel.CreditCardPayment(BankId, refNo, amount, cardInfo, ref errorMessage, ref provisionCode);
        }
        
        public bool CreditCardPaymentRefund(int BankId, string refNo, decimal amount, Atlas.Efes.OracleClient.OracleServiceProxy.creditCardInfo cardInfo, ref string errorMessage, ref string provisionCode) {
            return base.Channel.CreditCardPaymentRefund(BankId, refNo, amount, cardInfo, ref errorMessage, ref provisionCode);
        }
        
        public System.Data.DataSet getAnyProcByParams(string procName, Atlas.Efes.OracleClient.OracleServiceProxy.Params[] lstParams) {
            return base.Channel.getAnyProcByParams(procName, lstParams);
        }
        
        public System.Data.DataSet getMultipleCursor(string procName, Atlas.Efes.OracleClient.OracleServiceProxy.Params[] lstParams, string[] cursors) {
            return base.Channel.getMultipleCursor(procName, lstParams, cursors);
        }
        
        public System.Data.DataSet getReport(string procName, Atlas.Efes.OracleClient.OracleServiceProxy.Params[] lstParams, int cacheTime) {
            return base.Channel.getReport(procName, lstParams, cacheTime);
        }
        
        public System.Data.DataSet GetDATA(string LoadSP_, string SelectSQL_, string PrimaryKeyColumn, decimal PKID_) {
            return base.Channel.GetDATA(LoadSP_, SelectSQL_, PrimaryKeyColumn, PKID_);
        }
        
        public decimal ServerInsUpd(string TableName, string SaveSP, string PrimaryKeyColumn, int PKVALUE, Atlas.Efes.OracleClient.OracleServiceProxy.Params[] parameters) {
            return base.Channel.ServerInsUpd(TableName, SaveSP, PrimaryKeyColumn, PKVALUE, parameters);
        }
        
        public System.Data.DataSet getAnyProcByNamelessParam(string procName, Atlas.Efes.OracleClient.OracleServiceProxy.Params[] lstParams) {
            return base.Channel.getAnyProcByNamelessParam(procName, lstParams);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Atlas.Efes.OracleClient.OracleServiceProxy.sessionInfo1 Atlas.Efes.OracleClient.OracleServiceProxy.IService1.getCredential(Atlas.Efes.OracleClient.OracleServiceProxy.transactionApprover request) {
            return base.Channel.getCredential(request);
        }
        
        public string getCredential(Atlas.Efes.OracleClient.OracleServiceProxy.sessionInfo affiliateApprover, out string authKey, out string company, out string infoMail, out string password, out int paymentBank, out string salesMail, out string userName) {
            Atlas.Efes.OracleClient.OracleServiceProxy.transactionApprover inValue = new Atlas.Efes.OracleClient.OracleServiceProxy.transactionApprover();
            inValue.affiliateApprover = affiliateApprover;
            Atlas.Efes.OracleClient.OracleServiceProxy.sessionInfo1 retVal = ((Atlas.Efes.OracleClient.OracleServiceProxy.IService1)(this)).getCredential(inValue);
            authKey = retVal.authKey;
            company = retVal.company;
            infoMail = retVal.infoMail;
            password = retVal.password;
            paymentBank = retVal.paymentBank;
            salesMail = retVal.salesMail;
            userName = retVal.userName;
            return retVal.IP;
        }
        
        public Atlas.Efes.OracleClient.OracleServiceProxy.ServiceResult GetServiceResult(string procName, Atlas.Efes.OracleClient.OracleServiceProxy.Params[] lstParams) {
            return base.Channel.GetServiceResult(procName, lstParams);
        }
        
        public Atlas.Efes.OracleClient.OracleServiceProxy.ServiceResult GetServiceResultMulti(string procName, Atlas.Efes.OracleClient.OracleServiceProxy.Params[] lstParams, string[] lstCursors) {
            return base.Channel.GetServiceResultMulti(procName, lstParams, lstCursors);
        }
    }
}
