//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/cancelicon.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/closeview.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/deleteicon.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/historyicon.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/pdficon.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/save.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/wordicon.png")]


