//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://gib.gov.tr/vedop3/eFatura", ClrNamespace="gib.gov.tr.vedop3.eFatura")]

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://gib.gov.tr/vedop3/eFatura", ConfigurationName="EFaturaPortType")]
public interface EFaturaPortType
{
    
    // CODEGEN: Generating message contract since the operation getApplicationResponse is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="getApplicationResponse", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(gib.gov.tr.vedop3.eFatura.EFaturaFaultType), Action="getApplicationResponse", Name="EFaturaFault")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getApplicationResponseResponse getApplicationResponse(getApplicationResponse request);
    
    [System.ServiceModel.OperationContractAttribute(Action="getApplicationResponse", ReplyAction="*")]
    System.Threading.Tasks.Task<getApplicationResponseResponse> getApplicationResponseAsync(getApplicationResponse request);
    
    // CODEGEN: Generating message contract since the operation sendDocument is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="sendDocument", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(gib.gov.tr.vedop3.eFatura.EFaturaFaultType), Action="sendDocument", Name="EFaturaFault")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    sendDocumentResponse sendDocument(sendDocument request);
    
    [System.ServiceModel.OperationContractAttribute(Action="sendDocument", ReplyAction="*")]
    System.Threading.Tasks.Task<sendDocumentResponse> sendDocumentAsync(sendDocument request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gib.gov.tr/vedop3/eFatura")]
public partial class getAppRespRequestType
{
    
    private string instanceIdentifierField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string instanceIdentifier
    {
        get
        {
            return this.instanceIdentifierField;
        }
        set
        {
            this.instanceIdentifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gib.gov.tr/vedop3/eFatura")]
public partial class documentReturnType
{
    
    private string msgField;
    
    private string hashField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string msg
    {
        get
        {
            return this.msgField;
        }
        set
        {
            this.msgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string hash
    {
        get
        {
            return this.hashField;
        }
        set
        {
            this.hashField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/05/xmlmime")]
public partial class base64Binary
{
    
    private string contentTypeField;
    
    private byte[] valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string contentType
    {
        get
        {
            return this.contentTypeField;
        }
        set
        {
            this.contentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
    public byte[] Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gib.gov.tr/vedop3/eFatura")]
public partial class documentType
{
    
    private string fileNameField;
    
    private base64Binary binaryDataField;
    
    private string hashField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string fileName
    {
        get
        {
            return this.fileNameField;
        }
        set
        {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public base64Binary binaryData
    {
        get
        {
            return this.binaryDataField;
        }
        set
        {
            this.binaryDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string hash
    {
        get
        {
            return this.hashField;
        }
        set
        {
            this.hashField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gib.gov.tr/vedop3/eFatura")]
public partial class getAppRespResponseType
{
    
    private string applicationResponseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string applicationResponse
    {
        get
        {
            return this.applicationResponseField;
        }
        set
        {
            this.applicationResponseField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getApplicationResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gib.gov.tr/vedop3/eFatura", Order=0)]
    public getAppRespRequestType getAppRespRequest;
    
    public getApplicationResponse()
    {
    }
    
    public getApplicationResponse(getAppRespRequestType getAppRespRequest)
    {
        this.getAppRespRequest = getAppRespRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getApplicationResponseResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gib.gov.tr/vedop3/eFatura", Order=0)]
    public getAppRespResponseType getAppRespResponse;
    
    public getApplicationResponseResponse()
    {
    }
    
    public getApplicationResponseResponse(getAppRespResponseType getAppRespResponse)
    {
        this.getAppRespResponse = getAppRespResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class sendDocument
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gib.gov.tr/vedop3/eFatura", Order=0)]
    public documentType documentRequest;
    
    public sendDocument()
    {
    }
    
    public sendDocument(documentType documentRequest)
    {
        this.documentRequest = documentRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class sendDocumentResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gib.gov.tr/vedop3/eFatura", Order=0)]
    public documentReturnType documentResponse;
    
    public sendDocumentResponse()
    {
    }
    
    public sendDocumentResponse(documentReturnType documentResponse)
    {
        this.documentResponse = documentResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface EFaturaPortTypeChannel : EFaturaPortType, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EFaturaPortTypeClient : System.ServiceModel.ClientBase<EFaturaPortType>, EFaturaPortType
{
    
    public EFaturaPortTypeClient()
    {
    }
    
    public EFaturaPortTypeClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EFaturaPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EFaturaPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EFaturaPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getApplicationResponseResponse EFaturaPortType.getApplicationResponse(getApplicationResponse request)
    {
        return base.Channel.getApplicationResponse(request);
    }
    
    public getAppRespResponseType getApplicationResponse(getAppRespRequestType getAppRespRequest)
    {
        getApplicationResponse inValue = new getApplicationResponse();
        inValue.getAppRespRequest = getAppRespRequest;
        getApplicationResponseResponse retVal = ((EFaturaPortType)(this)).getApplicationResponse(inValue);
        return retVal.getAppRespResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getApplicationResponseResponse> EFaturaPortType.getApplicationResponseAsync(getApplicationResponse request)
    {
        return base.Channel.getApplicationResponseAsync(request);
    }
    
    public System.Threading.Tasks.Task<getApplicationResponseResponse> getApplicationResponseAsync(getAppRespRequestType getAppRespRequest)
    {
        getApplicationResponse inValue = new getApplicationResponse();
        inValue.getAppRespRequest = getAppRespRequest;
        return ((EFaturaPortType)(this)).getApplicationResponseAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    sendDocumentResponse EFaturaPortType.sendDocument(sendDocument request)
    {
        return base.Channel.sendDocument(request);
    }
    
    public documentReturnType sendDocument(documentType documentRequest)
    {
        sendDocument inValue = new sendDocument();
        inValue.documentRequest = documentRequest;
        sendDocumentResponse retVal = ((EFaturaPortType)(this)).sendDocument(inValue);
        return retVal.documentResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<sendDocumentResponse> EFaturaPortType.sendDocumentAsync(sendDocument request)
    {
        return base.Channel.sendDocumentAsync(request);
    }
    
    public System.Threading.Tasks.Task<sendDocumentResponse> sendDocumentAsync(documentType documentRequest)
    {
        sendDocument inValue = new sendDocument();
        inValue.documentRequest = documentRequest;
        return ((EFaturaPortType)(this)).sendDocumentAsync(inValue);
    }
}
namespace gib.gov.tr.vedop3.eFatura
{
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName="EFaturaFault", Namespace="http://gib.gov.tr/vedop3/eFatura", IsNullable=false)]
    public partial class EFaturaFaultType : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("EFaturaFaultType", "http://gib.gov.tr/vedop3/eFatura");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
}
