//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Efes.ReceiverIntegrationService.SenderIntegrationServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SenderIntegrationServiceProxy.ISenderIntegrationService")]
    public interface ISenderIntegrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderIntegrationService/SendDocument", ReplyAction="http://tempuri.org/ISenderIntegrationService/SendDocumentResponse")]
        Atlas.Efes.Common.ServiceModel.DocumentResponse SendDocument(Atlas.Efes.Common.ServiceModel.DocumentInfo documentInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderIntegrationService/SendDocumentVS2", ReplyAction="http://tempuri.org/ISenderIntegrationService/SendDocumentVS2Response")]
        Atlas.Efes.Common.ServiceModel.DocumentResponse SendDocumentVS2(Atlas.Efes.Common.GIB.StandardBusinessDocumentInfo standartBusiness);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISenderIntegrationService/GetApplicationResponse", ReplyAction="http://tempuri.org/ISenderIntegrationService/GetApplicationResponseResponse")]
        Atlas.Efes.Common.ServiceModel.ApplicationResponse GetApplicationResponse(string instanceIdentifier);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISenderIntegrationServiceChannel : Atlas.Efes.ReceiverIntegrationService.SenderIntegrationServiceProxy.ISenderIntegrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SenderIntegrationServiceClient : System.ServiceModel.ClientBase<Atlas.Efes.ReceiverIntegrationService.SenderIntegrationServiceProxy.ISenderIntegrationService>, Atlas.Efes.ReceiverIntegrationService.SenderIntegrationServiceProxy.ISenderIntegrationService {
        
        public SenderIntegrationServiceClient() {
        }
        
        public SenderIntegrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SenderIntegrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SenderIntegrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SenderIntegrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Atlas.Efes.Common.ServiceModel.DocumentResponse SendDocument(Atlas.Efes.Common.ServiceModel.DocumentInfo documentInfo) {
            return base.Channel.SendDocument(documentInfo);
        }
        
        public Atlas.Efes.Common.ServiceModel.DocumentResponse SendDocumentVS2(Atlas.Efes.Common.GIB.StandardBusinessDocumentInfo standartBusiness) {
            return base.Channel.SendDocumentVS2(standartBusiness);
        }
        
        public Atlas.Efes.Common.ServiceModel.ApplicationResponse GetApplicationResponse(string instanceIdentifier) {
            return base.Channel.GetApplicationResponse(instanceIdentifier);
        }
    }
}
