//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Efes.SenderIntegrationService.SignatureServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.signserver.ebg.tr/", ConfigurationName="SignatureServiceProxy.SignatureWS")]
    public interface SignatureWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.signserver.ebg.tr/SignatureWS/verifyRequest", ReplyAction="http://services.signserver.ebg.tr/SignatureWS/verifyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyResponse verify(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.signserver.ebg.tr/SignatureWS/signRequest", ReplyAction="http://services.signserver.ebg.tr/SignatureWS/signResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signResponse sign(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.signserver.ebg.tr/SignatureWS/signpdfRequest", ReplyAction="http://services.signserver.ebg.tr/SignatureWS/signpdfResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signpdfResponse signpdf(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signpdfRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.signserver.ebg.tr/SignatureWS/signCmsRequest", ReplyAction="http://services.signserver.ebg.tr/SignatureWS/signCmsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signCmsResponse signCms(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signCmsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.signserver.ebg.tr/SignatureWS/TestRequest", ReplyAction="http://services.signserver.ebg.tr/SignatureWS/TestResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.TestResponse Test(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.TestRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.signserver.ebg.tr/SignatureWS/writeNotDataRequest", ReplyAction="http://services.signserver.ebg.tr/SignatureWS/writeNotDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.writeNotDataResponse writeNotData(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.writeNotDataRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.signserver.ebg.tr/SignatureWS/verifyLevelRequest", ReplyAction="http://services.signserver.ebg.tr/SignatureWS/verifyLevelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyLevelResponse verifyLevel(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyLevelRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.signserver.ebg.tr/SignatureWS/timeStampRequest", ReplyAction="http://services.signserver.ebg.tr/SignatureWS/timeStampResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.timeStampResponse timeStamp(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.timeStampRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.signserver.ebg.tr/")]
    public partial class verifyResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private dataFile[] dataListField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private bool isVerifiedField;
        
        private signer[] signatureListField;
        
        private string verifyLogField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dataList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public dataFile[] dataList {
            get {
                return this.dataListField;
            }
            set {
                this.dataListField = value;
                this.RaisePropertyChanged("dataList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool isVerified {
            get {
                return this.isVerifiedField;
            }
            set {
                this.isVerifiedField = value;
                this.RaisePropertyChanged("isVerified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("signatureList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public signer[] signatureList {
            get {
                return this.signatureListField;
            }
            set {
                this.signatureListField = value;
                this.RaisePropertyChanged("signatureList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string verifyLog {
            get {
                return this.verifyLogField;
            }
            set {
                this.verifyLogField = value;
                this.RaisePropertyChanged("verifyLog");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.signserver.ebg.tr/")]
    public partial class dataFile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] dataFile1Field;
        
        private string fileNameField;
        
        private byte[] hashField;
        
        private string mimeTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dataFile", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] dataFile1 {
            get {
                return this.dataFile1Field;
            }
            set {
                this.dataFile1Field = value;
                this.RaisePropertyChanged("dataFile1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
                this.RaisePropertyChanged("hash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("mimeType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.signserver.ebg.tr/")]
    public partial class signatureResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private byte[] signedFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] signedFile {
            get {
                return this.signedFileField;
            }
            set {
                this.signedFileField = value;
                this.RaisePropertyChanged("signedFile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.signserver.ebg.tr/")]
    public partial class signer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isValidField;
        
        private string signerCertEffectiveDateField;
        
        private string signerCertExpiredDateField;
        
        private string signerCertIssuerField;
        
        private string signerCertSerialNumberField;
        
        private string signerCertSubjectField;
        
        private string signerNameField;
        
        private System.DateTime signingTimeField;
        
        private bool signingTimeFieldSpecified;
        
        private string tcKimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool isValid {
            get {
                return this.isValidField;
            }
            set {
                this.isValidField = value;
                this.RaisePropertyChanged("isValid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string signerCertEffectiveDate {
            get {
                return this.signerCertEffectiveDateField;
            }
            set {
                this.signerCertEffectiveDateField = value;
                this.RaisePropertyChanged("signerCertEffectiveDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string signerCertExpiredDate {
            get {
                return this.signerCertExpiredDateField;
            }
            set {
                this.signerCertExpiredDateField = value;
                this.RaisePropertyChanged("signerCertExpiredDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string signerCertIssuer {
            get {
                return this.signerCertIssuerField;
            }
            set {
                this.signerCertIssuerField = value;
                this.RaisePropertyChanged("signerCertIssuer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string signerCertSerialNumber {
            get {
                return this.signerCertSerialNumberField;
            }
            set {
                this.signerCertSerialNumberField = value;
                this.RaisePropertyChanged("signerCertSerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string signerCertSubject {
            get {
                return this.signerCertSubjectField;
            }
            set {
                this.signerCertSubjectField = value;
                this.RaisePropertyChanged("signerCertSubject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string signerName {
            get {
                return this.signerNameField;
            }
            set {
                this.signerNameField = value;
                this.RaisePropertyChanged("signerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime signingTime {
            get {
                return this.signingTimeField;
            }
            set {
                this.signingTimeField = value;
                this.RaisePropertyChanged("signingTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool signingTimeSpecified {
            get {
                return this.signingTimeFieldSpecified;
            }
            set {
                this.signingTimeFieldSpecified = value;
                this.RaisePropertyChanged("signingTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string tcKimlikNo {
            get {
                return this.tcKimlikNoField;
            }
            set {
                this.tcKimlikNoField = value;
                this.RaisePropertyChanged("tcKimlikNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verify", WrapperNamespace="http://services.signserver.ebg.tr/", IsWrapped=true)]
    public partial class verifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] signedData;
        
        public verifyRequest() {
        }
        
        public verifyRequest(byte[] signedData) {
            this.signedData = signedData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifyResponse", WrapperNamespace="http://services.signserver.ebg.tr/", IsWrapped=true)]
    public partial class verifyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyResult @return;
        
        public verifyResponse() {
        }
        
        public verifyResponse(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sign", WrapperNamespace="http://services.signserver.ebg.tr/", IsWrapped=true)]
    public partial class signRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] toSignedData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string certificateId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signatureId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short envelopedType;
        
        public signRequest() {
        }
        
        public signRequest(byte[] toSignedData, string certificateId, string signatureId, short envelopedType) {
            this.toSignedData = toSignedData;
            this.certificateId = certificateId;
            this.signatureId = signatureId;
            this.envelopedType = envelopedType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="signResponse", WrapperNamespace="http://services.signserver.ebg.tr/", IsWrapped=true)]
    public partial class signResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signatureResponse @return;
        
        public signResponse() {
        }
        
        public signResponse(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signatureResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="signpdf", WrapperNamespace="http://services.signserver.ebg.tr/", IsWrapped=true)]
    public partial class signpdfRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] toSignedPdf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string certificateId;
        
        public signpdfRequest() {
        }
        
        public signpdfRequest(byte[] toSignedPdf, string certificateId) {
            this.toSignedPdf = toSignedPdf;
            this.certificateId = certificateId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="signpdfResponse", WrapperNamespace="http://services.signserver.ebg.tr/", IsWrapped=true)]
    public partial class signpdfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signatureResponse @return;
        
        public signpdfResponse() {
        }
        
        public signpdfResponse(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signatureResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="signCms", WrapperNamespace="http://services.signserver.ebg.tr/", IsWrapped=true)]
    public partial class signCmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] toSignedData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CertificateId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isUsedTsa;
        
        public signCmsRequest() {
        }
        
        public signCmsRequest(byte[] toSignedData, string CertificateId, bool isUsedTsa) {
            this.toSignedData = toSignedData;
            this.CertificateId = CertificateId;
            this.isUsedTsa = isUsedTsa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="signCmsResponse", WrapperNamespace="http://services.signserver.ebg.tr/", IsWrapped=true)]
    public partial class signCmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signatureResponse @return;
        
        public signCmsResponse() {
        }
        
        public signCmsResponse(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signatureResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://services.signserver.ebg.tr/", IsWrapped=true)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] toTimeStampData;
        
        public TestRequest() {
        }
        
        public TestRequest(byte[] toTimeStampData) {
            this.toTimeStampData = toTimeStampData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://services.signserver.ebg.tr/", IsWrapped=true)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signatureResponse @return;
        
        public TestResponse() {
        }
        
        public TestResponse(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signatureResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="writeNotData", WrapperNamespace="http://services.signserver.ebg.tr/", IsWrapped=true)]
    public partial class writeNotDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool arg1;
        
        public writeNotDataRequest() {
        }
        
        public writeNotDataRequest(byte[] arg0, bool arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="writeNotDataResponse", WrapperNamespace="http://services.signserver.ebg.tr/", IsWrapped=true)]
    public partial class writeNotDataResponse {
        
        public writeNotDataResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifyLevel", WrapperNamespace="http://services.signserver.ebg.tr/", IsWrapped=true)]
    public partial class verifyLevelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] signedData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int verifiyLevel;
        
        public verifyLevelRequest() {
        }
        
        public verifyLevelRequest(byte[] signedData, int verifiyLevel) {
            this.signedData = signedData;
            this.verifiyLevel = verifiyLevel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifyLevelResponse", WrapperNamespace="http://services.signserver.ebg.tr/", IsWrapped=true)]
    public partial class verifyLevelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyResult @return;
        
        public verifyLevelResponse() {
        }
        
        public verifyLevelResponse(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timeStamp", WrapperNamespace="http://services.signserver.ebg.tr/", IsWrapped=true)]
    public partial class timeStampRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] toTimeStampData;
        
        public timeStampRequest() {
        }
        
        public timeStampRequest(byte[] toTimeStampData) {
            this.toTimeStampData = toTimeStampData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timeStampResponse", WrapperNamespace="http://services.signserver.ebg.tr/", IsWrapped=true)]
    public partial class timeStampResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.signserver.ebg.tr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public timeStampResponse() {
        }
        
        public timeStampResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SignatureWSChannel : Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignatureWSClient : System.ServiceModel.ClientBase<Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS>, Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS {
        
        public SignatureWSClient() {
        }
        
        public SignatureWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignatureWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignatureWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignatureWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyResponse Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS.verify(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyRequest request) {
            return base.Channel.verify(request);
        }
        
        public Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyResult verify(byte[] signedData) {
            Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyRequest inValue = new Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyRequest();
            inValue.signedData = signedData;
            Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyResponse retVal = ((Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS)(this)).verify(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signResponse Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS.sign(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signRequest request) {
            return base.Channel.sign(request);
        }
        
        public Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signatureResponse sign(byte[] toSignedData, string certificateId, string signatureId, short envelopedType) {
            Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signRequest inValue = new Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signRequest();
            inValue.toSignedData = toSignedData;
            inValue.certificateId = certificateId;
            inValue.signatureId = signatureId;
            inValue.envelopedType = envelopedType;
            Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signResponse retVal = ((Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS)(this)).sign(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signpdfResponse Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS.signpdf(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signpdfRequest request) {
            return base.Channel.signpdf(request);
        }
        
        public Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signatureResponse signpdf(byte[] toSignedPdf, string certificateId) {
            Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signpdfRequest inValue = new Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signpdfRequest();
            inValue.toSignedPdf = toSignedPdf;
            inValue.certificateId = certificateId;
            Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signpdfResponse retVal = ((Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS)(this)).signpdf(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signCmsResponse Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS.signCms(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signCmsRequest request) {
            return base.Channel.signCms(request);
        }
        
        public Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signatureResponse signCms(byte[] toSignedData, string CertificateId, bool isUsedTsa) {
            Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signCmsRequest inValue = new Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signCmsRequest();
            inValue.toSignedData = toSignedData;
            inValue.CertificateId = CertificateId;
            inValue.isUsedTsa = isUsedTsa;
            Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signCmsResponse retVal = ((Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS)(this)).signCms(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.TestResponse Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS.Test(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.signatureResponse Test(byte[] toTimeStampData) {
            Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.TestRequest inValue = new Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.TestRequest();
            inValue.toTimeStampData = toTimeStampData;
            Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.TestResponse retVal = ((Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS)(this)).Test(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.writeNotDataResponse Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS.writeNotData(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.writeNotDataRequest request) {
            return base.Channel.writeNotData(request);
        }
        
        public void writeNotData(byte[] arg0, bool arg1) {
            Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.writeNotDataRequest inValue = new Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.writeNotDataRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.writeNotDataResponse retVal = ((Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS)(this)).writeNotData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyLevelResponse Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS.verifyLevel(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyLevelRequest request) {
            return base.Channel.verifyLevel(request);
        }
        
        public Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyResult verifyLevel(byte[] signedData, int verifiyLevel) {
            Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyLevelRequest inValue = new Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyLevelRequest();
            inValue.signedData = signedData;
            inValue.verifiyLevel = verifiyLevel;
            Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.verifyLevelResponse retVal = ((Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS)(this)).verifyLevel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.timeStampResponse Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS.timeStamp(Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.timeStampRequest request) {
            return base.Channel.timeStamp(request);
        }
        
        public byte[] timeStamp(byte[] toTimeStampData) {
            Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.timeStampRequest inValue = new Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.timeStampRequest();
            inValue.toTimeStampData = toTimeStampData;
            Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.timeStampResponse retVal = ((Atlas.Efes.SenderIntegrationService.SignatureServiceProxy.SignatureWS)(this)).timeStamp(inValue);
            return retVal.@return;
        }
    }
}
